export { default as colors } from './colors'
export { default as components } from './components'
export { default as fonts } from './fonts'
export { default as sizes } from './sizes'
export { default as spaces } from './spaces'
